//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_Zero_Hunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollectRequest()
        {
            this.CollectedFoodByEmps = new HashSet<CollectedFoodByEmp>();
            this.FoodDistributions = new HashSet<FoodDistribution>();
        }
    
        public int CollectRequest_Id { get; set; }
        public string FoodDscription { get; set; }
        public string FoodType { get; set; }
        public string Quantity { get; set; }
        public string Expired_Time { get; set; }
        public string Address { get; set; }
        public int RestruentDonorId { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectedFoodByEmp> CollectedFoodByEmps { get; set; }
        public virtual RestruentDonor RestruentDonor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodDistribution> FoodDistributions { get; set; }
    }
}
