//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_Zero_Hunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodDistributionByEmployee
    {
        public int id { get; set; }
        public int Distribution_Id { get; set; }
        public int EmpId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual FoodDistribution FoodDistribution { get; set; }
    }
}
