//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_Zero_Hunger.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MidprojectEntities4 : DbContext
    {
        public MidprojectEntities4()
            : base("name=MidprojectEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CollectedFoodByEmp> CollectedFoodByEmps { get; set; }
        public virtual DbSet<CollectRequest> CollectRequests { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FoodDistribution> FoodDistributions { get; set; }
        public virtual DbSet<FoodDistributionByEmployee> FoodDistributionByEmployees { get; set; }
        public virtual DbSet<NGOAdmin> NGOAdmins { get; set; }
        public virtual DbSet<RestruentDonor> RestruentDonors { get; set; }
    }
}
